mammouth.Tokens = {
	NewToken: 'new',
	FunctionToken: 'function',
	IfToken: 'if',
	ElseToken: 'else',
	ForToken: 'for',
	ForeachToken: 'foreach',
	WhileToken: 'while',
	SwitchToken: 'switch',
	CaseToken: 'case',
	DefaultToken: 'default',
	TryToken: 'try',
	CatchToken: 'catch',
	FinallyToken: 'finally',
	NamespaceToken: 'namespace',
	ClassToken: 'class',
	ContinueToken: 'continue',
	BreakToken: 'break',
	EchoToken: 'echo',
	ReturnToken: 'return',
	IncludeToken: 'include',
	Include_onceToken: 'include_once',
	RequireToken: 'require',
	Require_onceToken: 'require_once'
};